name: Generate GitHub Stats

on:
  schedule:
    - cron: "0 * * * *" # roda a cada 1h
  workflow_dispatch: # permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Metrics embed
        uses: lowlighter/metrics@latest
        with:
          filename: assets/github-metrics.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          base: header, activity, community, repositories, metadata
          config_timezone: America/Sao_Paulo
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_details: percentage
